# Generated by Django 2.2 on 2019-04-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('registrar_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('registrar_id', models.CharField(max_length=11)),
                ('manufacturer', models.ManyToManyField(to='blockcaregh.Manufacturer')),
            ],
            options={
                'verbose_name': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('registrar_id', models.CharField(max_length=11)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockcaregh.Manufacturer')),
                ('pharmacy', models.ManyToManyField(to='blockcaregh.Pharmacy')),
            ],
        ),
    ]
